config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :groups, only: [:index, :new, :create, :destroy] do
    resources :entities, only: [:index, :new, :create, :destroy]
 end           
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :destroy, Group do |group|
        group.author_id == user.id
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, dependent: :destroy
  has_many :groups, through: :group_entities

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  attribute :user_id, :integer

  has_many :group_entities, dependent: :destroy
  has_many :entities, through: :group_entities

  has_one_attached :icon
  validates :name, :icon, presence: true
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity

  after_create :total_entities_group

  def total_entities_group
    group.increment!(:total_entities, entity.amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: :author_id
  has_many :entities, foreign_key: :author_id

  validates :name, presence: true, length: { minimum: 0, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path # replace about_path with the path you want it to redirect to
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @group = Group.find(params[:group_id])
    @group_entities = Group.find(params[:group_id]).group_entities.order(created_at: :desc)
  end

  # GET /entities/new
  def new
    @group = Group.find_by_id(params[:group_id])
    @available_groups = current_user.groups.reject { |f| @group.entities.include?(f) }
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = current_user.entities.new(name: params[:name], amount: params[:amount])

    if @entity.save
      @group_entity = GroupEntity.new(group_id: params[:groups], entity_id: @entity.id)
      @group_entity.save
      redirect_to group_entities_path(group_id: params[:groups]), notice: 'Your Transaction is created successfully'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Your category is created successfully'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    flash[:notice] = if @group.destroy
                       'Category removed successfully'
                     else
                       'Something went wrong'
                     end
    redirect_to about_path
  end

  private

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
    redirect_to about_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
</div>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
</div>

app/views/entities/index.html.erb
<section class="d-flex flex-column cont my-2">
  <div class="log-in d-flex justify-content-between align-items-center">
  <span> 
<%= link_to groups_path do %>
<%= image_tag "arrow-left-solid.svg", class: "icon"  %>
<% end %>
</span>
      <li class="headers"> <h2 class = "headers"> Transaction</h2></li>
      <%= button_to destroy_user_session_path, method: :delete, class:"btn" do %>   
        <%= image_tag "arrow-right-from-bracket-solid.svg", class:"icon" %>
      <% end %>               
  </div>

  <%= render partial: "shared/flash"%>
 
 <div class="d-flex justify-content-between card-custom-header p-3">
    <% if @group.icon.attached? %>
      <div class="d-flex gap-3 align-items-center">
        <img class="img" src="<%= url_for(@group.icon) %>">
        <p class="name-group-header"> <%= @group.name.capitalize %></p>
      </div>
    <% end %>
  
    <div class="align-self-center">
      <span class="name-group"> $<%= @group.total_entities %> </span>
    </div>
  </div>


<div class="container">
  <% @group_entities.each do |group_entity| %>
    <div class="groups d-flex justify-content-between card-custom my-3">
    <div class ="d-flex flex-column">
      <p class="name-group-header"> <%= group_entity.entity.name.capitalize %></p>
      <div class="date-style "><%= group_entity.created_at.strftime("%d %b %Y") %></div>
    </div>
    <span class="name-group"> $<%= group_entity.entity.amount %></span>
  </div>
  <% end %>
</div>

</section>

<div class="add-category">
  <%= link_to 'Add new Purchase', "/groups/#{@group.id}/entities/new", class:"btn btn-outline-light padding-purchase"  %>
</div>

app/views/entities/new.html.erb
<div class="log-in d-flex justify-content-between align-items-center">
<%= link_to group_entities_path do %>
  <%= image_tag "arrow-left-solid.svg", class: "icon"  %>
<% end %>
<li class="log"> <h2 class="headers"> ADD Transaction</h2></li>
<%= button_to destroy_user_session_path, method: :delete, class:"btn" do %>   
  <%= image_tag "arrow-right-from-bracket-solid.svg", class:"icon" %>
<% end %>
</div>

<%= render partial: "shared/flash"%>

<div class="container">
    <%= form_with url: group_entities_path, method: :post do |f| %>
      <div class="field">
        <%= f.label :name, class:"mt-2" %><br />
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name" %>
      </div>

      <div class="field">
        <%= f.label :amount, class:"mt-2" %><br />
        <%= f.text_field :amount, autofocus: true, class: "form-control", placeholder: "amount" %>
      </div>

      <div class="field">
        <%= f.label :groups, class:"mt-2" %><br />
        <%= f.select :groups, options_from_collection_for_select(@available_groups, 'id', 'name'), {}, { class: "form-control" }%>
      </div>

      <div class="actions add-category-end">
        <%= f.submit "ADD Transaction", class:"btn btn-outline-light padding-purchase" %>
      </div>

    <% end %>
  </div>

<br>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  

  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>

app/views/groups/_form.html.erb
<div class="container">
<%= render partial: "shared/flash"%>
<%= form_with(model: [@user, group]) do |form| %>
  
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%= form.label :name, class:"mt-2" %><br />
  <%= form.text_field :name, autofocus: true, class: "form-control", placeholder: "name" %>
</div>

<div class="field">
  <%= form.label :icon, class:"mt-2" %>
  <%= form.file_field :icon, class: "form-control" %>
</div>

  <div class: "actions add-category-end">
    <%= form.submit "Add", class: "add-category btn btn-outline-light padding-add-button" %>
 
  </div>
<% end %>
</div>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<section class="d-flex flex-column cont">
<div class="log-in d-flex justify-content-between align-items-center">
<%= image_tag "bars-solid.svg", class: "icon" %>
<li class="headers">
  <h2 class="headers">CATEGORIES</h2>
</li>
<%= button_to destroy_user_session_path, method: :delete, class:"btn" do %>   
  <%= image_tag "arrow-right-from-bracket-solid.svg", class:"icon" %>
<% end %>
</div>

<%= render partial: "shared/flash"%>

<% @groups.each do |group| %>
  <%= link_to "/groups/#{group.id}/entities", class: "text-decoration-none" do %>
    <div class="card-custom my-2 py-3 px-2 mb-3 px-5">
      <div class="card-body d-flex">
        <div class="d-flex align-items-center">
          <% if group.icon.attached? %>
            <div class="d-flex gap-2">
              <%= image_tag url_for(group.icon), class: "img" %>
            </div>
          <% end %>
          <div class="ms-3">
            <span class="name-group-header"><%= group.name %></span>
            <div class="date-style "><%= group.created_at.strftime("%d %b %Y") %></div>
          </div>
        </div>
        <div class="d-flex flex-column ms-auto">
          <span class="name-group text-center"><%= "$#{group.total_entities}" %></span>
          
           
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</section>
<div class="actions add-category-end">
  <%= link_to 'Add new Category', new_group_path, class: "btn btn-outline-light padding" %>
</div>

app/views/groups/new.html.erb
<section>
<div class="log-in d-flex justify-content-between align-items-center">

<%= link_to groups_path do %>
  <%= image_tag "arrow-left-solid.svg", class: "icon"  %>
<% end %>

<li class="log">
  <h2 class="headers">ADD CATEGORY</h2>
</li>
<%= button_to destroy_user_session_path, method: :delete, class:"btn" do %>   
  <%= image_tag "arrow-right-from-bracket-solid.svg", class:"icon" %>
<% end %>
</div>
<div class="container mt-5">
<%= render "form", group: @group %>
</div>
</section>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/home/index.html.erb
<%= render partial: "shared/flash"%>
<section class = "bodys d-flex flex-column justify-content-between align-items-center gap-2">
<div class = "text-center mb-5 mt-5">
<h1>BudgetApp</h1>
</div>
  <div class = "text-center ">
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark btn-lg" %>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-dark btn-lg" %>
    
  </div>
 
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-success alert-dismissible fade show" role="alert">
<strong><%= notice %></strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
<% if flash[:alert]%>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<strong> <%= alert %> </strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>